import { useEffect, useState } from 'react';
import { formatBytes } from '../../core/format/formatBytes';
import type { UiLanguage } from '../i18n';
import {
  fourCgsGalleryManifestUrl,
  loadFourCgsGalleryManifest,
  type FourCgsGalleryItem,
  type FourCgsGalleryManifest,
} from '../fourCgsGallery';
import './FourCgsGalleryDialog.css';

interface FourCgsGalleryDialogProps {
  readonly activeId: string | null;
  readonly language: UiLanguage;
  readonly onClose: () => void;
  readonly onSelect: (item: FourCgsGalleryItem, onProgress: (ratio: number) => void) => Promise<void>;
}

const COPY = {
  zh: {
    kicker: 'LOCAL 4CGS COLLECTION', title: '4CGS 测试相册',
    description: '来自 public/4cgs 的本地测试场景；快照由当前浏览器渲染器真实生成。',
    close: '关闭相册', empty: '相册中暂时没有 4CGS 文件。', loadingManifest: '正在读取相册…',
    loadFailed: '相册读取失败', open: '打开场景', opening: '正在读取', active: '当前场景',
    fileSize: '文件', frames: '帧', gaussians: '高斯', segments: '片段',
    frameRange: '源帧', compression: '压缩', updated: '清单更新',
  },
  en: {
    kicker: 'LOCAL 4CGS COLLECTION', title: '4CGS test gallery',
    description: 'Local test scenes from public/4cgs; snapshots are generated by the current browser renderer.',
    close: 'Close gallery', empty: 'There are no 4CGS files in the gallery yet.', loadingManifest: 'Loading gallery…',
    loadFailed: 'Gallery failed to load', open: 'Open scene', opening: 'Loading', active: 'Current scene',
    fileSize: 'File', frames: 'Frames', gaussians: 'Gaussians', segments: 'Segments',
    frameRange: 'Source', compression: 'Ratio', updated: 'Manifest',
  },
} as const;

// #WDD-gpt 2026-08-17 - 相册弹窗独立管理清单、缩略图、下载进度和错误，避免把资源浏览逻辑塞进主编辑器。
export function FourCgsGalleryDialog({ activeId, language, onClose, onSelect }: FourCgsGalleryDialogProps) {
  const copy = COPY[language];
  const [manifest, setManifest] = useState<FourCgsGalleryManifest | null>(null);
  const [manifestError, setManifestError] = useState<string | null>(null);
  const [loadingId, setLoadingId] = useState<string | null>(null);
  const [loadingProgress, setLoadingProgress] = useState(0);
  const [loadError, setLoadError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    loadFourCgsGalleryManifest(fourCgsGalleryManifestUrl())
      .then((nextManifest) => { if (!cancelled) setManifest(nextManifest); })
      .catch((error) => { if (!cancelled) setManifestError(error instanceof Error ? error.message : String(error)); });
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    if (loadingId) return;
    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key !== 'Escape') return;
      event.preventDefault();
      event.stopImmediatePropagation();
      onClose();
    };
    window.addEventListener('keydown', closeOnEscape, true);
    return () => window.removeEventListener('keydown', closeOnEscape, true);
  }, [loadingId, onClose]);

  const selectItem = async (item: FourCgsGalleryItem) => {
    if (loadingId) return;
    setLoadingId(item.id);
    setLoadingProgress(0);
    setLoadError(null);
    try {
      await onSelect(item, setLoadingProgress);
      onClose();
    } catch (error) {
      setLoadError(error instanceof Error ? error.message : String(error));
    } finally {
      setLoadingId(null);
    }
  };

  return (
    <div
      className="fourcgs-gallery-backdrop"
      data-camera-input-block
      onMouseDown={(event) => { if (event.target === event.currentTarget && !loadingId) onClose(); }}
    >
      <section aria-label={copy.title} aria-modal="true" className="fourcgs-gallery-dialog" role="dialog">
        <header className="fourcgs-gallery-header">
          <div>
            <span>{copy.kicker}</span>
            <strong>{copy.title}</strong>
            <p>{copy.description}</p>
          </div>
          <button aria-label={copy.close} disabled={Boolean(loadingId)} onClick={onClose} type="button">×</button>
        </header>

        <div className="fourcgs-gallery-content">
          {!manifest && !manifestError && <p className="fourcgs-gallery-state">{copy.loadingManifest}</p>}
          {manifestError && <p className="fourcgs-gallery-state error"><strong>{copy.loadFailed}</strong>{manifestError}</p>}
          {manifest?.items.length === 0 && <p className="fourcgs-gallery-state">{copy.empty}</p>}
          {manifest && manifest.items.length > 0 && (
            <div className="fourcgs-gallery-grid">
              {manifest.items.map((item) => {
                const loading = loadingId === item.id;
                const active = activeId === item.id;
                const compressionRatio = item.sourceBytes / Math.max(1, item.fileBytes);
                return (
                  <article className={`fourcgs-gallery-card${active ? ' active' : ''}`} key={item.id}>
                    <div className="fourcgs-gallery-snapshot">
                      <img alt={`${item.name} snapshot`} decoding="async" loading="lazy" src={item.snapshotUrl} />
                      <span>4CGS</span>
                      {active && <b>{copy.active}</b>}
                    </div>
                    <div className="fourcgs-gallery-card-body">
                      <div className="fourcgs-gallery-title">
                        <div><strong>{item.name}</strong><small>{item.codec}</small></div>
                        <em>{formatBytes(item.fileBytes)}</em>
                      </div>
                      <p>{item.description}</p>
                      <div className="fourcgs-gallery-tags">{item.tags.map((tag) => <span key={tag}>{tag}</span>)}</div>
                      <dl>
                        <div><dt>{copy.frames}</dt><dd>{item.frameCount}</dd></div>
                        <div><dt>{copy.gaussians}</dt><dd>{item.gaussianCount.toLocaleString(language === 'zh' ? 'zh-CN' : 'en-US')}</dd></div>
                        <div><dt>{copy.segments}</dt><dd>{item.segmentCount}</dd></div>
                        <div><dt>{copy.compression}</dt><dd>{compressionRatio.toFixed(2)}×</dd></div>
                      </dl>
                      <div className="fourcgs-gallery-card-footer">
                        <small>{copy.frameRange} {item.frameRange[0]}–{item.frameRange[1]}</small>
                        <button disabled={Boolean(loadingId)} onClick={() => void selectItem(item)} type="button">
                          {loading ? `${copy.opening} ${Math.round(loadingProgress * 100)}%` : copy.open}
                        </button>
                      </div>
                      {loading && <div className="fourcgs-gallery-progress"><i style={{ width: `${loadingProgress * 100}%` }} /></div>}
                    </div>
                  </article>
                );
              })}
            </div>
          )}
          {loadError && <p className="fourcgs-gallery-load-error" role="alert">{loadError}</p>}
        </div>
        {manifest && <footer>{manifest.items.length} 4CGS · {copy.updated} {manifest.updatedAt}</footer>}
      </section>
    </div>
  );
}
