import { Application, Entity, GSplatData, GSplatResource, Quat } from 'playcanvas';

const SH_C0 = 0.28209479177387814;
const GOLDEN_RATIO = 0.6180339887498949;
const SILVER_RATIO = 0.41421356237309503;

interface DemoGaussian {
  entity: Entity;
  splatCount: number;
  dispose: () => void;
}

function fract(value: number): number {
  return value - Math.floor(value);
}

function colorChannel(value: number): number {
  return (value - 0.5) / SH_C0;
}

export function createDemoGaussian(app: Application, count: number): DemoGaussian {
  const properties = new Map<string, Float32Array>();
  const names = [
    'x', 'y', 'z',
    'rot_0', 'rot_1', 'rot_2', 'rot_3',
    'scale_0', 'scale_1', 'scale_2',
    'f_dc_0', 'f_dc_1', 'f_dc_2',
    'opacity',
  ];

  for (const name of names) {
    properties.set(name, new Float32Array(count));
  }

  const prop = (name: string) => {
    const value = properties.get(name);
    if (!value) {
      throw new Error(`Missing generated Gaussian property: ${name}`);
    }
    return value;
  };

  const rotation = new Quat();

  //WDD-gpt 2026-08-14 - 生成无外部网络依赖的真实 GSplat 数据，保证首次启动即可验证渲染管线。
  for (let i = 0; i < count; i += 1) {
    const u = fract(i * GOLDEN_RATIO) * Math.PI * 2;
    const v = fract(i * SILVER_RATIO) * Math.PI * 2;
    const variation = 0.035 * Math.sin(i * 1.731);
    const ring = 0.86 + (0.31 + variation) * Math.cos(v);

    prop('x')[i] = Math.cos(u) * ring;
    prop('y')[i] = 0.84 + Math.sin(v) * (0.31 + variation);
    prop('z')[i] = Math.sin(u) * ring;

    rotation.setFromEulerAngles(v * 180 / Math.PI, -u * 180 / Math.PI, 18 * Math.sin(u * 3));
    prop('rot_0')[i] = rotation.w;
    prop('rot_1')[i] = rotation.x;
    prop('rot_2')[i] = rotation.y;
    prop('rot_3')[i] = rotation.z;

    const scale = 0.035 + 0.012 * (0.5 + 0.5 * Math.sin(i * 0.91));
    prop('scale_0')[i] = scale * 1.6;
    prop('scale_1')[i] = scale * 0.72;
    prop('scale_2')[i] = scale;

    const pulse = 0.5 + 0.5 * Math.sin(u * 2 - v);
    const red = 0.14 + 0.64 * pulse;
    const green = 0.52 + 0.36 * (1 - pulse);
    const blue = 0.88 + 0.1 * Math.cos(v);
    prop('f_dc_0')[i] = colorChannel(red);
    prop('f_dc_1')[i] = colorChannel(green);
    prop('f_dc_2')[i] = colorChannel(blue);
    prop('opacity')[i] = 0.84;
  }

  const data = new GSplatData([{
    name: 'vertex',
    count,
    properties: names.map((name) => ({
      type: 'float',
      name,
      storage: prop(name),
      byteSize: Float32Array.BYTES_PER_ELEMENT,
    })),
  }], ['Generated by Dong Editor 3']);
  data.activated = true;
  data.reorderData();

  const resource = new GSplatResource(app.graphicsDevice, data);
  const entity = new Entity('Default Gaussian');
  entity.addComponent('gsplat');
  entity.gsplat!.resource = resource;
  app.root.addChild(entity);

  let disposed = false;
  return {
    entity,
    splatCount: count,
    dispose: () => {
      if (disposed) {
        return;
      }
      disposed = true;
      entity.destroy();
      resource.destroy();
    },
  };
}
